backend:
  name: git-gateway
  branch: master

collections:
  - label: Links
    name: links
    folder: src/cms/collections/links
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Time", name: "publishTime", widget: datetime }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Destination URL", name: "destinationUrl", widget: "string" }
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Link", value: "link" }
          - { label: "Video", value: "video" }

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow
