localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: Links
    name: links
    folder: src/cms/links
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Time", name: "publishTime", widget: datetime }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Destination URL", name: "destinationUrl", widget: "string" }
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Link", value: "link" }
          - { label: "Video", value: "video" }

  - label: Recipes
    name: reicpes
    folder: src/cms/recipes
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Time", name: "publishTime", widget: datetime }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Hero Background", name: "heroBackground", widget: "image" }
      - {
          label: "Hero Title",
          name: "heroTitle",
          widget: "string",
          required: false,
        }
      - {
          label: "Youtube ID",
          name: "youtubeID",
          widget: "string",
          required: false,
        }
      - label: "Prep Time"
        name: "prepTime"
        widget: object
        fields:
          - { label: Measurement, name: measurement, widget: string }
          - label: Unit
            name: unit
            widget: select
            default: "minute"
            options:
              - { label: "Minute(s)", value: "minute" }
              - { label: "Hours(s)", value: "hour" }
      - label: "Cook/Bake Time"
        name: "cookTime"
        widget: object
        fields:
          - { label: Measurement, name: measurement, widget: string }
          - label: Unit
            name: unit
            widget: select
            default: "minute"
            options:
              - { label: "Minute(s)", value: "minute" }
              - { label: "Hours(s)", value: "hour" }
          - label: Activity
            name: activity
            widget: select
            default: "bake"
            options:
              - { label: "Bake", value: "bake" }
              - { label: "Cook", value: "cook" }
              - { label: "Active", value: "active" }
      - { label: "Servings", name: "servings", widget: "string" }
      - label: "Ingredient Sections"
        name: "ingredientSections"
        widget: "list"
        fields:
          - { label: "Section Title", name: title, widget: string }
          - label: "Ingredients"
            name: "ingredients"
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Measurement, name: measurement, widget: string }
              - label: Unit
                name: unit
                widget: select
                required: false
                default: ""
                options:
                  - { label: "_blank_", value: "" }
                  - { label: "Teaspoon (tsp)", value: "teaspoon" }
                  - { label: "Tablespoon (tbsp)", value: "tablespoon" }
                  - { label: "Cup", value: "cup" }
                  - { label: "Gram", value: "gram" }
                  - { label: "Ounce", value: "ounce" }
                  - { label: "Fluid Ounce", value: "fluid ounce" }
                  - { label: "Pinch", value: "pinch" }
                  - { label: "Dash", value: "dash" }
                  - { label: "Pint", value: "pint" }
                  - { label: "Quart", value: "quart" }
                  - { label: "Gallon", value: "gallon" }
      - label: "Recipe Sections"
        name: "recipeSections"
        widget: "list"
        fields:
          - label: Instructions
            name: instructions
            widget: markdown
            buttons: ["bold", "italic", "link", "image", "bulleted-list"]
          - {
              label: "Top Image",
              name: "topImage",
              widget: "image",
              required: false,
            }
          - {
              label: "Bottom Image",
              name: "bottomImage",
              widget: "image",
              required: false,
            }
