backend:
  name: git-gateway
  branch: publish

collections:
  - label: Links
    name: links
    folder: src/cms/collections/links
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Destination URL", name: "destinationUrl", widget: "string" }
      - { label: "Publish Time", name: "publishTime", widget: datetime }

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
